using UnityEngine;
using UnityEngine.InputSystem;
using TMPro;
using Roguelite.Player;

namespace Roguelite.UI
{
    /// <summary>
    /// Component gắn vào NPC Shop trong Scene.
    /// Tự động nhận diện khoảng cách khi Player bước đến gần (không cần chém đòn đánh),
    /// hiện dòng nhắc [E] Mo Shop trên đầu NPC và nhấn E để mở/đóng cửa hàng.
    /// Version: 1.6.0
    /// </summary>
    public class ShopNPCInteractable : MonoBehaviour
    {
        public const string VERSION = "1.6.0";

        [Header("--- Shop Controller Reference ---")]
        [Tooltip("Kéo GameObject chứa ShopUIController (ShopCanvas hoặc ShopPanel) vào đây. Nếu để trống sẽ tự động tìm.")]
        [SerializeField] private ShopUIController customShopUIController;

        [Header("--- Interaction Proximity Settings ---")]
        [Tooltip("Bán kính vùng tương tác quanh NPC (Player bước vào bán kính này là nhận diện ngay lập tức).")]
        [SerializeField] private float interactionRadius = 2.5f;

        [Tooltip("Phím bấm để tương tác mở Shop (Mặc định: Phím E).")]
        [SerializeField] private KeyCode interactKey = KeyCode.E;

        [Tooltip("UI gợi ý bấm phím (Tùy chọn: Nếu để trống, script sẽ tự tạo Text nổi '[E] Mo Shop' trên đầu NPC).")]
        [SerializeField] private GameObject interactionPrompt;

        [Tooltip("Nội dung dòng nhắc hiện trên đầu NPC.")]
        [SerializeField] private string promptText = "[E] Mo Shop";

        [Tooltip("Độ cao của dòng chữ gợi ý so với tâm NPC (Mặc định: 1.5).")]
        [SerializeField] private float promptHeightOffset = 1.5f;

        [Tooltip("Tự động đóng Shop khi người chơi đi ra khỏi phạm vi NPC.")]
        [SerializeField] private bool autoCloseOnExit = true;

        [Header("--- Optional Audio ---")]
        [SerializeField] private AudioClip interactSFX;

        private bool isPlayerInRange = false;
        private Transform playerTransform;
        private GameObject autoGeneratedPrompt;

        private void Awake()
        {
            EnsurePromptExists();
        }

        private void Start()
        {
            FindPlayerTransform();
        }

        private void LateUpdate()
        {
            // Đảm bảo NPC luôn ở Z = 0 trong không gian 2D
            if (transform.position.z != 0f)
            {
                Vector3 pos = transform.position;
                pos.z = 0f;
                transform.position = pos;
            }
        }

        private void EnsurePromptExists()
        {
            if (interactionPrompt != null)
            {
                interactionPrompt.transform.localPosition = new Vector3(0, promptHeightOffset, 0);
                if (interactionPrompt.TryGetComponent<TextMeshPro>(out var existingTmp))
                {
                    existingTmp.text = promptText;
                    existingTmp.sortingOrder = 100;
                }
                interactionPrompt.SetActive(false);
                return;
            }

            // Tự động tạo TextMeshPro World Space nổi trên đầu NPC nếu người dùng chưa gắn UI thủ công
            autoGeneratedPrompt = new GameObject("AutoInteractionPrompt");
            autoGeneratedPrompt.transform.SetParent(transform);
            autoGeneratedPrompt.transform.localPosition = new Vector3(0, promptHeightOffset, 0);

            TextMeshPro tmp = autoGeneratedPrompt.AddComponent<TextMeshPro>();
            tmp.text = promptText;
            tmp.fontSize = 4.5f;
            tmp.alignment = TextAlignmentOptions.Center;
            tmp.color = new Color(1f, 0.9f, 0.2f, 1f); // Màu vàng sáng
            tmp.sortingOrder = 100;

            interactionPrompt = autoGeneratedPrompt;
            interactionPrompt.SetActive(false);
        }

        private void Update()
        {
            // 1. Kiểm tra khoảng cách thực tế giữa Player và NPC
            CheckPlayerProximity();

            // 2. Bấm phím tương tác để mở hoặc đóng Shop khi đang trong phạm vi (hỗ trợ cả New Input System & Legacy)
            if (isPlayerInRange && IsInteractKeyDown())
            {
                InteractWithShop();
            }
        }

        private bool IsInteractKeyDown()
        {
            if (Keyboard.current != null)
            {
                switch (interactKey)
                {
                    case KeyCode.E: if (Keyboard.current.eKey.wasPressedThisFrame) return true; break;
                    case KeyCode.F: if (Keyboard.current.fKey.wasPressedThisFrame) return true; break;
                    case KeyCode.Space: if (Keyboard.current.spaceKey.wasPressedThisFrame) return true; break;
                    case KeyCode.Return: if (Keyboard.current.enterKey.wasPressedThisFrame) return true; break;
                }
            }

            return Input.GetKeyDown(interactKey);
        }

        private void CheckPlayerProximity()
        {
            if (playerTransform == null)
            {
                FindPlayerTransform();
                if (playerTransform == null) return;
            }

            float distance = Vector2.Distance(transform.position, playerTransform.position);
            
            // Hysteresis: Bán kính vào là interactionRadius, bán kính ra là interactionRadius + 0.5f để chống rung ranh giới
            float effectiveRadius = isPlayerInRange ? (interactionRadius + 0.5f) : interactionRadius;
            isPlayerInRange = distance <= effectiveRadius;

            ShopUIController controller = GetShopController();
            bool isShopOpen = controller != null && controller.IsOpen;

            // Hiển thị Prompt khi Player trong tầm và Shop đang đóng
            bool shouldShowPrompt = isPlayerInRange && !isShopOpen;
            if (interactionPrompt != null && interactionPrompt.activeSelf != shouldShowPrompt)
            {
                interactionPrompt.SetActive(shouldShowPrompt);
            }

            // Tự động đóng Shop khi đi ra ngoài phạm vi
            if (!isPlayerInRange && autoCloseOnExit && controller != null && isShopOpen)
            {
                controller.CloseShop();
            }
        }

        private void FindPlayerTransform()
        {
            PlayerController pc = FindFirstObjectByType<PlayerController>();
            if (pc != null)
            {
                playerTransform = pc.transform;
                return;
            }

            GameObject pGo = GameObject.FindGameObjectWithTag("Player");
            if (pGo != null)
            {
                playerTransform = pGo.transform;
            }
        }

        public void InteractWithShop()
        {
            ShopUIController controller = GetShopController();
            if (controller == null)
            {
                Debug.LogWarning("[ShopNPCInteractable] Không tìm thấy ShopUIController trong Scene! Hãy kéo ShopCanvas/ShopPanel vào ô 'Custom Shop UI Controller'.");
                return;
            }

            controller.ToggleShop();

            // Cập nhật ngay trạng thái Prompt sau khi toggle
            if (interactionPrompt != null)
            {
                interactionPrompt.SetActive(!controller.IsOpen);
            }

            if (interactSFX != null && Camera.main != null)
            {
                AudioSource.PlayClipAtPoint(interactSFX, transform.position);
            }
        }

        private ShopUIController GetShopController()
        {
            if (customShopUIController != null) return customShopUIController;
            return ShopUIController.Instance;
        }

        // Hỗ trợ thêm cả Trigger nếu NPC có Collider2D Trigger
        private void OnTriggerEnter2D(Collider2D collision)
        {
            if (IsPlayer(collision))
            {
                if (playerTransform == null) playerTransform = collision.transform;
                CheckPlayerProximity();
            }
        }

        private void OnTriggerExit2D(Collider2D collision)
        {
            if (IsPlayer(collision))
            {
                CheckPlayerProximity();
            }
        }

        private bool IsPlayer(Collider2D col)
        {
            if (col == null) return false;
            if (col.CompareTag("Player")) return true;
            if (col.GetComponent<PlayerController>() != null || col.GetComponentInParent<PlayerController>() != null) return true;
            if (col.GetComponent<PlayerStats>() != null || col.GetComponentInParent<PlayerStats>() != null) return true;
            return col.gameObject.name.ToLower().Contains("player");
        }

        private void OnDrawGizmosSelected()
        {
            Gizmos.color = new Color(0f, 1f, 1f, 0.4f);
            Gizmos.DrawWireSphere(transform.position, interactionRadius);
        }
    }
}
